name: Deploy Quartz site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Dependencies
        run: npm ci
      - name: Build Quartz
        run: npx quartz build
      - name: Add robots.txt at root
        run: |
          echo "User-agent: *\nAllow: /\nSitemap: https://escaperr94.github.io/sitemap.xml" > public/robots.txt
      - name: Move Google verification file to root
        run: |
          if [ -f public/static/google0b6ea17f9bf0b7e6.html ]; then
            mv public/static/google0b6ea17f9bf0b7e6.html public/google0b6ea17f9bf0b7e6.html
          fi
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

